source 'https://rubygems.org'

gem 'rake'
gem 'jekyll'
gem 'rouge'
gem 'jekyll-spaceship'
gem 'jekyll-pandoc'
gem 'tufte-pandoc-jekyll'
gem 'gemoji'
gem "webrick", "~> 1.8"
gem 'nokogiri'
gem 'jekyll-data-pages'
gem 'commonmarker'
gem 'pristine ffi'
gem 'pristine racc'
gem 'pristine sass-embedded'
gem 'pristine unf_ext'